# Site settings
title: billwiens.com
email: billwiens@gmail.com
description: >
  We are the Internet.
baseurl: ""
url: "http://billwiens.com" # the base hostname & protocol for your site
twitter_username: billwiens
github_username:  billputer

# Build settings
markdown: kramdown
timezone: "America/Los_Angeles"

exclude:
- Gemfile
- Gemfile.lock
- README.md