# Site settings
title: billwiens.com
email: billwiens@gmail.com
description: >
  We are the Internet.
baseurl: ""
url: "http://billwiens.com"
logo: logo.png
twitter_username: billwiens
github_username:  billputer

# Owner/author information
owner:
  name: Bill Wiens
  avatar: profile/bill-wolf-large.jpg
  email: billwiens@gmail.com
  # Social networking links used in footer.
  twitter: billwiens
  facebook: billwiens
  github: billputer
  instagram: billputer

# Build settings
markdown: kramdown
timezone: "America/Los_Angeles"

links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Blog
    url: /blog

exclude:
- Gemfile
- Gemfile.lock
- README.md