# Site settings
title: billwiens.com
email: billwiens@gmail.com
description: >
  We are the Internet.
baseurl: ""
url: "http://127.0.0.1:4000"
logo: logo.png

# Owner/author information
owner:
  name: Bill Wiens
  avatar: profile/bill-wolf-large.jpg
  email: billwiens@gmail.com
  # Social networking links used in footer.
  twitter: billwiens
  facebook: billwiens
  github: billputer
  instagram: billputer

google_analytics: UA-12361421-1

# Build settings
markdown: kramdown
timezone: "America/Los_Angeles"

links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Blog
    url: /blog

exclude:
- Gemfile
- Gemfile.lock
- README.md
- tasks
